from .audio_nodes import NODE_CLASS_MAPPINGS as AUDIO_CLASS, NODE_DISPLAY_NAME_MAPPINGS as AUDIO_DISPLAY
from .sigma_node import NODE_CLASS_MAPPINGS as SIGMA_CLASS, NODE_DISPLAY_NAME_MAPPINGS as SIGMA_DISPLAY

NODE_CLASS_MAPPINGS = {**AUDIO_CLASS, **SIGMA_CLASS}
NODE_DISPLAY_NAME_MAPPINGS = {**AUDIO_DISPLAY, **SIGMA_DISPLAY}

WEB_DIRECTORY = "js" 

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']

print("\n\033[92m[老李-工具箱]\033[0m 插件已加载！")